Just some thoughts
Mrcubix/Color-Tiles.Avalonia pull request #1
Opened 2023-09-08 13:55 UTC by timunie

- Use DataTemplates
- Use Commands
- Use less events in the end :-)

2023-09-09 16:52 UTC, Mrcubix requested changes
I 'm sorry but i don't feel like this is going one bit in a direction that's going to avoid me or anyone else who might want to contribute, the weirdest quirks one might have to face trying to build an Avalonia powered app this way.

Trying to avoid any form of routing since it cause many strange issue when using Avalonia specifically.

Some of the removed events are vitals to other elements such as starting a new game properly as well as setting up the HUD.
Unless you have a simpler alternative to what i'm doing, just removing them won't do.

2023-09-09 16:52 UTC, Mrcubix commented on ColorTiles/ViewModels/MainViewModel.cs
> +    public object CurrentMenu
I don't like where this is going

2023-09-09 16:52 UTC, Mrcubix commented on ColorTiles/ViewModels/MainViewModel.cs
> +        if (!TryLoadImageAsset("tilesets/Color-Tiles.png", out IImage? image))
i forgot about linux, oops

2023-09-09 16:52 UTC, Mrcubix commented on ColorTiles/Views/Controls/GameBoard.axaml
> +            <DataTemplate DataType="entities:ColorTile">
Wasn't able to achieve what i wanted using this, nor Uniform grid since it was implemented with a 3rd of the features, and even then it's generous.

Will end up overriding Render in a future commit, already done writing that part.

2023-09-09 16:52 UTC, Mrcubix commented on ColorTiles/ViewModels/Menus/MainMenuViewModel.cs
> +        _Parent.CurrentMenu = _Parent.GameOverMenuViewModel;
I don't like this one bit, i should had make those ViewModels private to make it more explicit that i don't intend stuff like this to happen.

2023-09-09 16:52 UTC, Mrcubix commented on ColorTiles/Views/MainView.axaml
> +        <ContentControl Content="{Binding CurrentMenu}">
And just like that, my fears came to fruition, with the numbers of quirks in avalonia caused by any form of routing, i have been trying to avoid stuff like this in my recent apps using avalonia.

2023-09-09 16:52 UTC, Mrcubix commented on ColorTiles/Views/MainView.axaml.cs
> -    protected override void OnDataContextBeginUpdate()
Some of those events are still necessary in order to properly start a game as well as setup the HUD properly

2023-09-09 16:59 UTC, Mrcubix requested changes
I 'm sorry but i don't feel like this is going one bit in a direction that's going to avoid me or anyone else who might want to contribute, the weirdest quirks one might have to face trying to build an Avalonia powered app this way.

Trying to avoid any form of routing since it cause many strange issue when using Avalonia specifically.

Some of the removed events are vitals to other elements such as starting a new game properly as well as setting up the HUD.
Unless you have a simpler alternative to what i'm doing, just removing them won't do.

2023-09-09 16:59 UTC, Mrcubix commented on ColorTiles/ViewModels/MainViewModel.cs
> +
I don't like where this is going

2023-09-09 16:59 UTC, Mrcubix commented on ColorTiles/ViewModels/Menus/MainMenuViewModel.cs
>      }
I don't like this one bit, i should had make those ViewModels private to make it more explicit that i don't intend stuff like this to happen.

2023-09-09 16:59 UTC, Mrcubix commented on ColorTiles/Views/Controls/GameBoard.axaml
>          </ItemsRepeater.ItemTemplate>
Wasn't able to achieve what i wanted using this, nor Uniform grid since it was implemented with a 3rd of the features, and even then, i'm being generous.

Will end up overriding Render in a future commit, already done writing that part.

2023-09-09 16:59 UTC, Mrcubix commented on ColorTiles/Views/MainView.axaml
> +        </ContentControl>
And just like that, my fears came to fruition, with the numbers of quirks in avalonia caused by any form of routing, i have been trying to avoid stuff like this in my recent apps using avalonia.

2023-09-09 16:59 UTC, Mrcubix commented on ColorTiles/Views/MainView.axaml.cs
> -    }
Some of those events are still necessary in order to properly start a game as well as setup the HUD properly

2023-09-09 16:59 UTC, Mrcubix commented on ColorTiles/Views/Menus/MainMenu.axaml.cs
> -        }
Same thing as before here

2023-09-11 02:45 UTC, Mrcubix commented
Superseded by 8 commits (4 majors)

2023-09-11 02:45 UTC, closed without merging

2023-09-11 06:06 UTC, timunie commented
I give up. I am not willing to write the entire App for you. Just wanted to point out how things work in general. But we have complete different Approaches of doing things. I don't say that yours is wrong, it is just not my cup of tea. So I'll leave it to you. I whish you success anyway.

2023-09-11 15:20 UTC, Mrcubix commented
Writing an entire app was not the point, i was expecting to learn another approach, not prone to issues present in Avalonia since at least a year ago (routing).

I removed most of the DataContextChanged jank 
 to viewmodels and subscribed to neccessary events directly from MainView using the DataContext.

Still not entirely statisfied with that approach but, i find it better than the way it was before.